apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: filer
spec:
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30001
    - name: service
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: minio
