apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
  namespace: filer
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 90
      targetPort: 9090
      nodePort: 30001
  selector:
    app: minio
