apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: filer
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30002
  selector:
    app: postgres
