// <auto-generated />
using System;
using Filer.TelegramBot.Presentation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Filer.TelegramBot.Presentation.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241110184939_AddUserWorkflows")]
    partial class AddUserWorkflows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Filer.TelegramBot.Presentation.UserStates.UserCallback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CallbackPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("callback_payload");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_callbacks");

                    b.ToTable("user_callbacks", (string)null);
                });

            modelBuilder.Entity("Filer.TelegramBot.Presentation.UserStates.UserState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_workflow_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_states");

                    b.HasIndex("CurrentWorkflowId")
                        .HasDatabaseName("ix_user_states_current_workflow_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_states_user_id");

                    b.ToTable("user_states", (string)null);
                });

            modelBuilder.Entity("Filer.TelegramBot.Presentation.UserStates.UserWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkflowPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("workflow_payload");

                    b.HasKey("Id")
                        .HasName("pk_user_workflows");

                    b.ToTable("user_workflows", (string)null);
                });

            modelBuilder.Entity("Filer.TelegramBot.Presentation.UserStates.UserState", b =>
                {
                    b.HasOne("Filer.TelegramBot.Presentation.UserStates.UserWorkflow", "CurrentWorkflow")
                        .WithMany()
                        .HasForeignKey("CurrentWorkflowId")
                        .HasConstraintName("fk_user_states_user_workflows_current_workflow_id");

                    b.Navigation("CurrentWorkflow");
                });
#pragma warning restore 612, 618
        }
    }
}
