// <auto-generated />
using System;
using Filer.TelegramBot.Presentation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Filer.TelegramBot.Presentation.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241108231147_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Filer.TelegramBot.Presentation.UserStates.UserState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Workflow")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("workflow");

                    b.Property<string>("WorkflowData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("workflow_data");

                    b.Property<string>("WorkflowStep")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("workflow_step");

                    b.HasKey("Id")
                        .HasName("pk_user_states");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_states_user_id");

                    b.ToTable("user_states", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
