apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-persistent-volume
  namespace: filer
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
