apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-volume-claim
  namespace: filer
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: grafana-persistent-volume
