apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: filer
spec:
  ports:
    - name: web
      port: 30003
      protocol: TCP
      targetPort: 3000
  sessionAffinity: None
  type: NodePort
  selector:
    app: grafana
