apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secrets
  namespace: filer
type: Opaque
data:
  TelegramIntegration__BotConfiguration__BotToken: ${TELEGRAM_BOT_TOKEN_BASE64}
  Test__Variables: Test
