apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-service
  namespace: filer
  labels:
    app: telegram-bot
spec:
  selector:
    app: telegram-bot
  type: NodePort
  ports:
    - port: 80
      nodePort: 31364
      targetPort: 8080
      protocol: TCP
      name: http
