apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seq-persistent-volume-claim
  namespace: filer
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
