apiVersion: v1
kind: PersistentVolume
metadata:
  name: seq-persistent-volume
  namespace: filer
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/seq"
