apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: filer
  labels:
    app: seq
spec:
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
    - name: service
      protocol: TCP
      port: 5341
      targetPort: 5341
  selector:
    app: seq
