apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: filer
  labels:
    app: seq
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: seq
