apiVersion: v1
kind: Secret
metadata:
  name: storage-secrets
  namespace: filer
type: Opaque
data:
  ConnectionStrings__Database: ${STORAGE_POSTGRES_CONNECTION_STRING}
  Minio__Endpoint: ${MINIO_ENDPOINT}
  Minio__AccessKey: ${MINIO_ROOT_USER}
  Minio__SecretKey: ${MINIO_ROOT_PASSWORD}
