apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: filer
  labels:
    app: storage
spec:
  selector:
    app: storage
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
