apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: filer
  labels:
    app: storage
spec:
  selector:
    app: storage
  type: NodePort
  ports:
    - port: 80
      nodePort: 31002
      targetPort: 8080
      protocol: TCP
      name: http
