name: "Deploy Grafana"
on:
  push:
    branches: ["master"]
    paths:
      ["infra/grafana/kubernetes/**", ".github/workflows/grafana.deploy.yaml"]
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy Grafana"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: "Copy Kubernetes files to server"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          source: "infra/grafana/kubernetes/"
          target: /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/grafana
          strip_components: 3

      - name: "Apply Kubernetes files"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          proxy_host: ${{ secrets.PROXY_SSH_HOST }}
          proxy_username: ${{ secrets.PROXY_SSH_USERNAME }}
          proxy_password: ${{ secrets.PROXY_SSH_PASSWORD }}
          proxy_port: ${{ secrets.PROXY_SSH_PORT }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/grafana/persistentVolume.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/grafana/persistentVolumeClaim.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/grafana/deployment.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S microk8s kubectl apply -f /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/grafana/service.yaml

            echo ${{ secrets.SSH_PASSWORD }} | sudo -S rm -rf /home/${{ secrets.SSH_USERNAME }}/github/kubernetes/grafana
